package com.morocco2030.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserPermissionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserPermissionAllPropertiesEquals(UserPermission expected, UserPermission actual) {
        assertUserPermissionAutoGeneratedPropertiesEquals(expected, actual);
        assertUserPermissionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserPermissionAllUpdatablePropertiesEquals(UserPermission expected, UserPermission actual) {
        assertUserPermissionUpdatableFieldsEquals(expected, actual);
        assertUserPermissionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserPermissionAutoGeneratedPropertiesEquals(UserPermission expected, UserPermission actual) {
        assertThat(actual)
            .as("Verify UserPermission auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserPermissionUpdatableFieldsEquals(UserPermission expected, UserPermission actual) {
        assertThat(actual)
            .as("Verify UserPermission relevant properties")
            .satisfies(a -> assertThat(a.getGrantedAt()).as("check grantedAt").isEqualTo(expected.getGrantedAt()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserPermissionUpdatableRelationshipsEquals(UserPermission expected, UserPermission actual) {
        assertThat(actual)
            .as("Verify UserPermission relationships")
            .satisfies(a -> assertThat(a.getPermission()).as("check permission").isEqualTo(expected.getPermission()));
    }
}
